apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: zeir-ingress
    annotations:
      #nginx.ingress.kubernetes.io/rewrite-target: /
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/issuer: "letsencrypt-production"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/app-root: "/opensrp"
spec:
  rules:
  - host: zeir-openmrs.bluecodeltd.com
    http:
      paths:
      - path:
        backend:
          serviceName: openmrs-service
          servicePort: 8080
  - host: zeir-opensrp.bluecodeltd.com
    http:
      paths:
      - path:
        backend:
          serviceName: opensrp-service
          servicePort: 8080
  - host: openmrs.zeir.smartregister.org
    http:
      paths:
      - path:
        backend:
          serviceName: openmrs-service
          servicePort: 8080
  - host: zeir.smartregister.org
    http:
      paths:
      - path:
        backend:
          serviceName: opensrp-service
          servicePort: 8080
  - host: zeir-data.bluecodeltd.com
    http:
      paths:
      - path:
        backend:
          serviceName: superset-service
          servicePort: 8088
